
    create table tb_automovel (
       id bigint generated by default as identity,
        ano varchar(255) not null,
        marca varchar(255) not null,
        modelo varchar(255) not null,
        preco_fipe varchar(255),
        primary key (id)
    );

    create table tb_usuario (
       id bigint generated by default as identity,
        cpf varchar(255) not null,
        data_de_nascimento date not null,
        email varchar(255) not null,
        nome varchar(255) not null,
        primary key (id)
    );

    create table tb_usuario_automoveis (
       usuario_id bigint not null,
        automovel_id bigint not null,
        primary key (usuario_id, automovel_id)
    );

    alter table tb_usuario 
       add constraint UK_594wib8ansybtilla48x7vdld unique (cpf);

    alter table tb_usuario 
       add constraint UK_spmnyb4dsul95fjmr5kmdmvub unique (email);

    alter table tb_usuario_automoveis 
       add constraint FK1fy86qcj0hy5wwkmwp4vlmh5t 
       foreign key (automovel_id) 
       references tb_automovel;

    alter table tb_usuario_automoveis 
       add constraint FK2exoomofjin3xm7sdnc3npm0j 
       foreign key (usuario_id) 
       references tb_usuario;

    